VALIDATION:
  metrics:
    cla:
      - _target_: sklearn.metrics.accuracy_score
    seg:
      - _target_: monai.metrics.DiceMetric

  save_best_metric:
    - accuracy_score
    - DiceMetric